# Justfile - for running scripts
# https://github.com/casey/just/

list:
    just -l

clean:
    rm -rf node_modules

install:
    pnpm install

run:
    pnpm run dev

build:
    pnpm run build

deploy: build
    cd ../../activity-pages && git pull
    cp -r dist/* ../../activity-pages/
    cd ../../activity-pages && git add . && git commit -m "Deploy UI $(date -u +"%Y-%m-%dT%H:%M:%SZ")" #&& git push
